// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Codemirror: typeof import('./src/components/Codemirror.vue')['default']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    MonacoEditor: typeof import('./src/components/MonacoEditor.vue')['default']
    Sandbox: typeof import('./src/components/sandbox/index.vue')['default']
  }
}
